title: Nevermore Academy
author: Totengeist
email: me@totengeist.com
url: https://www.wednesdayseries.com
description: > # this means to ignore newlines until "twitter_username:"
  A fan site for the Netflix series Wednesday.

# social links
rss: rss
logo: img/nevermore_logo.png

show_excerpts: true # set to true to show excerpts on the homepage
google_analytics: G-QWXPDCT547
lang: en-US

  
pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num' # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  trail: 
    before: 2
    after: 2

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: "/:year/:month/:title.html"

# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
date_format: "%b %-d, %Y"
date_format_yearless: "%b %-d"
time_format: "%I:%M %P"

# Build settings
markdown: kramdown
plugins:
 - jekyll-index-pages
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-redirect-from
 - jekyll-paginate-v2

index_pages:
  categories:
    title: Posts about :label
    excerpt: Posts about :label
    per_page: 5
    permalink: /category/:label/
    layout: index
  tags:
    title: Posts about :label
    excerpt: Posts about :label
    per_page: 5
    permalink: /tag/:label/
    layout: index

kramdown:
    footnote_backlink: "⤴"
